import pygame
pygame.mixer.init()
jump = pygame.mixer.Sound("Assets/Sounds/jump.wav")
shoot_1 = pygame.mixer.Sound("Assets/Sounds/shoot_1.wav")
shoot_2 = pygame.mixer.Sound("Assets/Sounds/shoot_2.wav")
tile_break = pygame.mixer.Sound("Assets/Sounds/break.wav")
tile_disappear = pygame.mixer.Sound("Assets/Sounds/pop.wav")
button = pygame.mixer.Sound("Assets/Sounds/button.wav")
monster =  pygame.mixer.Sound("Assets/Sounds/monster.wav")
fall =  pygame.mixer.Sound("Assets/Sounds/fall.wav")
thump =  pygame.mixer.Sound("Assets/Sounds/thump.wav")
die_1 =  pygame.mixer.Sound("Assets/Sounds/die_1.wav")
die_2 =  pygame.mixer.Sound("Assets/Sounds/die_2.wav")
suck = pygame.mixer.Sound("Assets/Sounds/suck.wav")
spring = pygame.mixer.Sound("Assets/Sounds/spring.wav")
trampoline = pygame.mixer.Sound("Assets/Sounds/trampoline.wav")
jetpack = pygame.mixer.Sound("Assets/Sounds/jetpack.wav")
propeller = pygame.mixer.Sound("Assets/Sounds/propeller.wav")
block = pygame.mixer.Sound("Assets/Sounds/block.wav")
activate_shield = pygame.mixer.Sound("Assets/Sounds/activate_shield.wav")
explosion = pygame.mixer.Sound("Assets/Sounds/explode.wav")

ufo = pygame.mixer.Sound("Assets/Sounds/ufo.wav")
ufo_suck = pygame.mixer.Sound("Assets/Sounds/ufo_suck.wav")

